### List all messages

GET http://localhost:3000/messages


### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "The POS 2"
}

### Get a particular messages
GET http://localhost:3000/messages/9185